version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../frontend/dist:/app/public
      - .env:/app/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_DATABASE: "${DB_DATABASE:-nuova_mobilita}"
      MYSQL_USER: "${DB_USERNAME:-utente}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
